// Created by Crowbar 0.74

$modelname "woowz_map/cavediver_dream/trees/fern.mdl"

$staticprop

$bodygroup "Body"
{
	studio "fern.smd"
}


$surfaceprop "foliage"

$contents "solid"

$illumposition -2.01 -1.932 2.632

$cdmaterials "woowz_map/cavediver_dream/props/trees/"

$cbox 0 0 0 0 0 0

$bbox -52.968 -56.316 -21.674 56.831 52.295 26.938

$definebone "static_prop" "" 0 0 0 0 0 0 0 0 0 0 0 0


$sequence "idle" "fern.smd"
